[08/Mar/2019 07:53:30] ERROR [usereview.movie_inventory:94] Erro while fetching movie info gu
[08/Mar/2019 07:53:30] ERROR [usereview.movie_inventory:95] Usereview matching query does not exist.
[08/Mar/2019 07:55:32] ERROR [usereview.movie_inventory:18] Movie details not found for robot 2.0
[08/Mar/2019 07:55:32] ERROR [usereview.movie_inventory:19] Movies matching query does not exist.
[08/Mar/2019 07:59:25] ERROR [django.request:135] Internal Server Error: /movie/review
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/manish/DataGlen/movies/usereview/views.py", line 38, in post
    code, msg = add_user_review(name, rate, comment)
  File "/home/manish/DataGlen/movies/usereview/movie_inventory.py", line 72, in add_user_review
    LOGGER.error("Movie Review not added for "+name.lower()+" adding new entry")
NameError: global name 'name' is not defined
[08/Mar/2019 07:59:25] ERROR [django.server:124] "POST /movie/review HTTP/1.1" 500 15661
[08/Mar/2019 08:03:22] ERROR [usereview.movie_inventory:72] Movie Review not added for robot 2.0 adding new entry
[08/Mar/2019 08:03:22] ERROR [usereview.movie_inventory:73] Usereview matching query does not exist.
